version: "3.9"

services:
  web:
    build: .
    image: rostelecom-chat-app
    container_name: rostelecom-chat-app
    restart: always
    environment:
      - GIGATOKEN=OWZiNzRmNzItYTM4YS00ZjdhLTgzOGQtMTQ0ODg4YmVjNzU0OmIwNzVjNzFmLTlhNzgtNDkxOC04Y2U4LTFlOWQzNDY4MDNlZQ==
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=chat_db
      - DATABASE_USER=chat_user
      - DATABASE_PASSWORD=strong_psw
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      pg:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    ports:
      - "80:8000"
    volumes:
      - ./static:/app/static
      - ./templates:/app/template
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  pg:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=chat_db
      - POSTGRES_USER=chat_user
      - POSTGRES_PASSWORD=strong_psw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  qdrant:
    build:
      context: ./qdrant
    image: qdrant-with-healthcheck
    container_name: qdrant
    restart: always
    environment:
      - QDRANT__TELEMETRY_DISABLED=true
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:6333/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  postgres_data:
  qdrant_data:
